# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  portfoliowebapi:
    image: portfoliowebapi
    build:
      context: .
      #dockerfile: Portfolio.WebApi/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5050:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - portfoliowebapi=${DB_CONN}
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
