@Portfolio.WebApi_HostAddress = http://localhost:8080

GET {{Portfolio.WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{Portfolio.WebApi_HostAddress}}/client/
Accept: application/json


